# Generated by Django 2.2.9 on 2020-07-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piroquiz', '0002_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('schoolans', models.CharField(max_length=255)),
                ('foodans', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Correct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolans', models.CharField(max_length=255)),
                ('foodans', models.CharField(max_length=255)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='piroquiz.Answer')),
            ],
        ),
        migrations.DeleteModel(
            name='CreateQuiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
